//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class accbankaccounts
    {
        [Key]
        public int idAccBankAccounts { get; set; }
        public int accounts_idAccounts { get; set; }
        public string bank_name { get; set; }
        public Nullable<int> iban { get; set; }
        public Nullable<int> control_number { get; set; }
        public string accountnumber { get; set; }
        public Nullable<int> accountadress_id { get; set; }
    }
}
