//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountadresses
    {
        public int idAccountAdresses { get; set; }
        public int account_idaccount { get; set; }
        public string phone { get; set; }
        public string street { get; set; }
        public string numbp1 { get; set; }
        public string numbp2 { get; set; }
        public string town { get; set; }
        public short is_main_adress { get; set; }
    
        public virtual account account { get; set; }
    }
}
