//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class accpayments
    {
        [Key]
        public int idAccPayments { get; set; }
        public Nullable<int> account_id_account { get; set; }
        public Nullable<int> project_id_project { get; set; }
        public string AccPaymentscol { get; set; }
    }
}
