//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientsearch
    {
        [Key]
        public int idClientSearch { get; set; }
        public int Account_idAccount { get; set; }
        public string search_phrase { get; set; }
        public Nullable<System.DateTime> search_date { get; set; }
    
        public virtual account account { get; set; }
    }
}
