//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class coursesgroups
    {
        public int id_courses_group { get; set; }
        public int Course_idCourse { get; set; }
        public int studygroups_group_number { get; set; }
    
        public virtual course course { get; set; }
        public virtual studygroups studygroups { get; set; }
    }
}
