//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class developer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public developer()
        {
            this.devavailabilitydetailed = new HashSet<devavailabilitydetailed>();
            this.projectdeveloper = new HashSet<projectdeveloper>();
            this.stageteam = new HashSet<stageteam>();
            this.technologiesdeveloper = new HashSet<technologiesdeveloper>();
        }

        [Key]
        public int id_developer { get; set; }
        public int Account_idAccount { get; set; }
        public string experience_from { get; set; }
        public string per_hour_cost { get; set; }
        public string week_availability { get; set; }
        public string whoiam { get; set; }
        public short isSuspendedForJobs { get; set; }
    
        public virtual account account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<devavailabilitydetailed> devavailabilitydetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectdeveloper> projectdeveloper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stageteam> stageteam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<technologiesdeveloper> technologiesdeveloper { get; set; }
    }
}
