//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class dictionary
    {

        [Key]
        public int idDictionary { get; set; }
        public Nullable<int> group { get; set; }
        public Nullable<int> entity { get; set; }
        public Nullable<int> smallEntity { get; set; }
        public string display { get; set; }
        public Nullable<short> isActive { get; set; }
        public Nullable<int> smallEntityOrder { get; set; }
        public Nullable<short> is_in_dropdown_list { get; set; }
        public Nullable<int> access_level { get; set; }
    }
}
