//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class lessonsdetails
    {
        public int id_lessons_details { get; set; }
        public Nullable<int> lessons_id_lessons { get; set; }
        public string ld_overview { get; set; }
        public string ld_topic { get; set; }
    
        public virtual lessons lessons { get; set; }
    }
}
