//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_tags
    {
        [Key]
        public int idpost_tags { get; set; }
        public Nullable<int> post_id { get; set; }
        public int Post_post_id { get; set; }
        public int tags_id_tags { get; set; }
    
        public virtual post post { get; set; }
        public virtual tags tags { get; set; }
    }
}
