//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectdata
    {
        [Key]
        public int idProjectData { get; set; }
        public int Project_ProjectId { get; set; }
        public string ProjectDataDir { get; set; }
    
        public virtual project project { get; set; }
    }
}
