//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectstage
    {
        public int idProjectStage { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string death_line { get; set; }
        public string stage_number { get; set; }
        public int Project_id { get; set; }
    
        public virtual project project { get; set; }
    }
}
