//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class projecttype
    {
        public int idProjectType { get; set; }
        public Nullable<int> description { get; set; }
        public Nullable<int> Dictionary_idDictionary { get; set; }
    }
}
