//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotorcourses
    {
        [Key]
        public int idPromotorCourses { get; set; }
        public int techpromotor_id_tech_promotor { get; set; }
        public int courses_id_courses { get; set; }
    
        public virtual courses courses { get; set; }
        public virtual technologypromotor technologypromotor { get; set; }
    }
}
