//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruitmenttest
    {
        [Key]
        public int idRecruitmentTest { get; set; }
        public int Account_idAccount { get; set; }
        public string api { get; set; }
        public string test_accepted { get; set; }
        public string test_finished { get; set; }
        public string timeForTest { get; set; }
        public Nullable<short> test_result { get; set; }
        public string test_valid_to_date { get; set; }
        public string user_comment { get; set; }
        public string feedback { get; set; }
        public Nullable<int> feedback_accountID { get; set; }
    
        public virtual account account { get; set; }
    }
}
