//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Toci.Mvcexample.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class stages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stages()
        {
            this.stageteam = new HashSet<stageteam>();
        }

        [Key]
        public int idStages { get; set; }
        public int Project_idProject { get; set; }
        public Nullable<int> Stage_number { get; set; }
        public Nullable<System.DateTime> start_stage_date { get; set; }
        public Nullable<System.DateTime> end_stage_date { get; set; }
        public Nullable<short> Stage_accepted { get; set; }
        public Nullable<int> Stage_leaderDeveloperId { get; set; }
        public string StageOpis { get; set; }
        public Nullable<int> StageStatus { get; set; }
    
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stageteam> stageteam { get; set; }
    }
}
