//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.DesignPatterns.ExceptionHandling.ErrorLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string CustomFrontMessage { get; set; }
        public string BackendMessage { get; set; }
        public System.DateTime OccurenceDatetime { get; set; }
    }
}
