//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Mvcexample.Models.CoursesSearch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursesSearchEntities : DbContext
    {
        public CoursesSearchEntities()
            : base("name=CoursesSearchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCourse_KeyWord> tblCourse_KeyWord { get; set; }
        public virtual DbSet<tblCourses> tblCourses { get; set; }
        public virtual DbSet<tblKeywords> tblKeywords { get; set; }
    }
}
