//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Mvcexample.Models.CoursesSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourse_KeyWord
    {
        public int ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> KeyWord_ID { get; set; }
    
        public virtual tblCourses tblCourses { get; set; }
        public virtual tblKeywords tblKeywords { get; set; }
    }
}
